services:
  nginx-modsecurity:
    image: owasp/modsecurity-crs:4.7.0-nginx-202410090410
    ports:
      - "80:80"
    volumes:
      - ./html-files:/html-files
      #- ./nginx-config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
    command: nginx -g "daemon off;"