services:
  nginx-modsecurity:
    image: owasp/modsecurity-crs:4.7.0-nginx-202410090410
    container_name: modsecurity-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVERNAME: localhost
      PARANOIA: 2 #slightly higher than basic
      BLOCKING_PARANOIA: 2 #slightly higher than basic
      ANOMALY_INBOUND: 4
      ANOMALY_OUTBOUND: 3
      MODSEC_AUDIT_LOG: /var/log/nginx/modsec_audit.log
      MODSEC_AUDIT_LOG_FORMAT: JSON
    volumes:
      - ./html-files:/html-files
      # Mount default.conf as a template:
      - ./nginx-config/conf.d/default.conf:/etc/nginx/templates/conf.d/default.conf.template
      # Mount nginx.conf as a template:
      - ./nginx-config/nginx.conf:/etc/nginx/templates/nginx.conf.template
      # Mount a logs directory on the host:
      - ./logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    env_file:
      - ./dev.env
