services:
  nginx-modsecurity:
    image: owasp/modsecurity-crs:4.7.0-nginx-202410090410
    container_name: modsecurity-nginx
    ports:
      - "8080:8080" # Use ports 8080 and 8443 as specified by the documentation.
      - "8443:8443"
    environment:
      SERVERNAME: localhost
      PARANOIA: 1 #the default and provides a balanced level of security with fewer false positives (4 is max)
      BLOCKING_PARANOIA: 1 #rules that block traffic based on detected issues
      ANOMALY_INBOUND: 5 #A setting of 5 is a standard threshold for balanced protection without overly sensitive blocking
      ANOMALY_OUTBOUND: 4 #Outbound checks focus on responses going back to the client
      MODSEC_AUDIT_LOG: /var/log/nginx/modsec_audit.log
      MODSEC_AUDIT_LOG_FORMAT: JSON
    volumes:
      - ./html-files:/html-files
      # Mount default.conf as a template:
      - ./nginx-config/conf.d/default.conf:/etc/nginx/templates/conf.d/default.conf.template
      # Mount nginx.conf as a template:
      - ./nginx-config/nginx.conf:/etc/nginx/templates/nginx.conf.template
      # Mount a logs directory on the host:
      - ./logs:/var/log/nginx  
    env_file:
      - ./dev.env  
