services:
  web:
    build:
      context: ./django/
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      # This was the original config file that we used throughout the tutorial, it is going to be replaced with the templates
      #- ./nginx/conf.d/:/etc/nginx/conf.d/
      # This is what we use when we have the environment variables:
      - ./nginx/templates/:/etc/nginx/templates
      - static_files:/home/app/staticfiles
      - ./nginx/pwd:/etc/pwd
      - ./nginx/secure/:/home/secure/
    env_file:
      - ./.env/dev.env

volumes:
  static_files:
